### ISSUE TITLE
Uninitialized header fields

### ISSUE THREAD

**Issue by wdtj** [Kakikou/pico-http-client#2]
I ported your code to my Pico project and attempted to run a portion of your example.  It returned a 400.  Looking at the actual request, I found garbage in the query string.  To fix this I changed the parse_url code to initialize unspecified header fields to empty strings:

`static url_t parse_url(const char *url) {
    url_t result;

    char scheme[10]="", domain[64]="", port[64]="", path[1024]="", query[1024]="";
    if (sscanf(url, "%9[^:]://%63[^:?]:%63[^/?]%1023[^?]%1023s", scheme, domain, port, path, query) < 4) {
        sscanf(url, "%9[^:]://%63[^:/?]%1023[^?]%1023s", scheme, domain, path, query);
        port[0] = '8';
        port[1] = '0';
        port[2] = 0;
    }`
It now works correctly.

**Comment by wdtj** [comment]
Thanks for the code.  I fail to see why the Raspberry Pi folks have not created something like this.

**Comment by Kakikou** [comment]
Hi,
Thank you for your feedback. I'm gonna fix it right now !
I also don't understand why they don't implement it in the sdk...
